name = "missionaries-cannibals"
version = "0.1.0"
defaultTargets = ["missionaries-cannibals"]

[[lean_lib]]
name = "MissionariesCannibals"

[[lean_exe]]
name = "missionaries-cannibals"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"